version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    container_name: my-node-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
